JAMAB_homepage:
    pattern:  /
    defaults: { _controller: JazzySpaceAulasMentorAlimentosBundle:Default:index }

JAMAB_listar:
    pattern:  /listar
    defaults: { _controller: JazzySpaceAulasMentorAlimentosBundle:Default:listar }

JAMAB_insertar:
    pattern:  /insertar
    defaults: { _controller: JazzySpaceAulasMentorAlimentosBundle:Default:insertar }

JAMAB_buscar:
    pattern:  /buscar
    defaults: { _controller: JazzySpaceAulasMentorAlimentosBundle:Default:buscarPorNombre }

JAMAB_ver:
    pattern:  /ver/{id}
    defaults: { _controller: JazzySpaceAulasMentorAlimentosBundle:Default:ver }
